# Generated by Django 6.1.1 on 2026-09-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
