# Generated by Django 6.1.1 on 2026-09-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
