# Generated by Django 6.1.1 on 2026-09-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoa_nome_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='estado_civil',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
