# Generated by Django 6.1.1 on 2026-09-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pessoa_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_entrada',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
