# Generated by Django 6.1.1 on 2026-09-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pessoa_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='origen_cadastro',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
